# Generated by Django 5.1.7 on 2025-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('compositor', models.CharField(max_length=200)),
                ('instrumento', models.CharField(max_length=100)),
                ('dificultad', models.CharField(max_length=50)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='partituras/')),
            ],
        ),
    ]
