# Generated by Django 5.1.7 on 2025-03-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertorio', '0002_categoria_delete_partitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('repertorio', models.CharField(choices=[('actual', 'Repertorio Actual'), ('villancicos', 'Villancicos'), ('otros', 'Otros Repertorios'), ('inedito', 'Inédito'), ('olvidadas', 'Canciones Olvidadas')], max_length=20)),
                ('archivo', models.FileField(upload_to='partituras/')),
            ],
        ),
    ]
