# Generated by Django 5.1.7 on 2025-03-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertorio', '0003_cancion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='archivo',
        ),
        migrations.AddField(
            model_name='cancion',
            name='bajo_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para bajo', null=True, upload_to='midis/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='baritono_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para barítono', null=True, upload_to='midis/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='contralto2_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para contralto 2', null=True, upload_to='midis/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='contralto_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para contralto', null=True, upload_to='midis/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='mezzosoprano_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para mezzosoprano', null=True, upload_to='midis/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='partitura',
            field=models.FileField(blank=True, help_text='Archivo PDF de la partitura', null=True, upload_to='partituras/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='soprano_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para soprano', null=True, upload_to='midis/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='tenor2_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para tenor 2', null=True, upload_to='midis/'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='tenor_midi',
            field=models.FileField(blank=True, help_text='Archivo MIDI para tenor', null=True, upload_to='midis/'),
        ),
    ]
