# Generated by Django 5.1.7 on 2025-03-28 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_delete_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerda', models.CharField(choices=[('soprano', 'Soprano'), ('mezzosoprano', 'Mezzosoprano'), ('contralto', 'Contralto'), ('tenor', 'Tenor'), ('baritono', 'Barítono'), ('bajo', 'Bajo')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
